src/Entity/Album.php
<?php

namespace App\Entity;

use App\Repository\AlbumRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Attribute\Groups;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: AlbumRepository::class)]
class Album
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups(['read'])]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    #[Groups(['read', 'create', 'update'])]
    #[Assert\NotBlank(groups: ['create'])]
    private ?string $name = null;

    #[ORM\Column]
    #[Groups(['read', 'create', 'update'])]
    #[Assert\NotBlank(groups: ['create'])]
    private ?int $year = null;

    #[ORM\Column]
    #[Groups(['read', 'create', 'update'])]
    private ?int $artist_id = null;

    /**
     * @var Collection<int, Artist>
     */
    #[ORM\ManyToMany(targetEntity: Artist::class, inversedBy: 'albums')]
    #[Groups(['read', 'create', 'update'])]
    private Collection $artist;

    /**
     * @var Collection<int, Track>
     */
    #[ORM\ManyToMany(targetEntity: Track::class, mappedBy: 'album')]
    #[Groups(['read', 'create', 'update'])]
    private Collection $tracks;

    public function __construct()
    {
        $this->artist = new ArrayCollection();
        $this->tracks = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getYear(): ?int
    {
        return $this->year;
    }

    public function setYear(int $year): static
    {
        $this->year = $year;

        return $this;
    }

    public function getArtistId(): ?int
    {
        return $this->artist_id;
    }

    public function setArtistId(int $artist_id): static
    {
        $this->artist_id = $artist_id;

        return $this;
    }

    /**
     * @return Collection<int, Artist>
     */
    public function getArtist(): Collection
    {
        return $this->artist;
    }

    public function addArtist(Artist $artist): static
    {
        if (!$this->artist->contains($artist)) {
            $this->artist->add($artist);
        }

        return $this;
    }

    public function removeArtist(Artist $artist): static
    {
        $this->artist->removeElement($artist);

        return $this;
    }

    /**
     * @return Collection<int, Track>
     */
    public function getTracks(): Collection
    {
        return $this->tracks;
    }

    public function addTrack(Track $track): static
    {
        if (!$this->tracks->contains($track)) {
            $this->tracks->add($track);
            $track->addAlbum($this);
        }

        return $this;
    }

    public function removeTrack(Track $track): static
    {
        if ($this->tracks->removeElement($track)) {
            $track->removeAlbum($this);
        }

        return $this;
    }
}

src/Form/AlbumType.php
<?php

namespace App\Form;

use App\Entity\Album;
use App\Entity\Artist;
use App\Entity\Track;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AlbumType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('year')
            ->add('artist_id')
            ->add('artist', EntityType::class, [
                'class' => Artist::class,
                'choice_label' => 'id',
                'multiple' => true,
            ])
            ->add('tracks', EntityType::class, [
                'class' => Track::class,
                'choice_label' => 'id',
                'multiple' => true,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Album::class,
        ]);
    }
}

src/Controller/Api/AlbumController.php
<?php

namespace App\Controller\Api;

use App\Entity\Album;
use App\Repository\AlbumRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpKernel\Attribute\MapRequestPayload;
use Symfony\Component\Serializer\Normalizer\AbstractNormalizer;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Messenger\Transport\Serialization\SerializerInterface;
use Symfony\Component\Serializer; 
//tentative pour regler le probleme de method undefined alors qu'elle est défini dans SerializerInterface.php

class AlbumController extends AbstractController
{
    public function __construct(
        private AlbumRepository $albumRepository,
        private EntityManagerInterface $em,
        private SerializerInterface $serializer
    )
    {
        
    }

    #[Route('/api/album', name: 'app_api_album', methods: ['GET'])]
    public function index(): JsonResponse
    {
        $album = $this->albumRepository->findAll();

        return $this->json([
            'album' => $album,
        ], 200, [], [
            'groups' => ['read']
        ]);
    }

    #[Route('/api/album/{id}', name: 'app_api_album_get', methods: ['GET'])]
    public function get(?Album $album = null): JsonResponse
    {
        
        if(!$album)
        {
            return $this->json([
                'error' => 'Album does not exist',
            ], 404);
        }

        return $this->json($album, 200, [], [
            'groups' => ['read']
        ]);
    }

    #[Route('/api/album', name: 'app_api_album_add', methods: ['POST'])]
    public function add( #[MapRequestPayload('json', ['groups' => ['create']])] Album $album
    ): JsonResponse
    {
        $this->em->persist($album);
        $this->em->flush();

        return $this->json($album, 200, [], [
            'groups' => ['read']
        ]);
    }

    // #[Route('/api/album/{id}', name: 'app_api_album_update',  methods: ['PUT'])]
    // public function update(Album $album, Request $request): JsonResponse
    // {
        
    //     $data = $request->getContent();
    //     $this->serializer->deserialize($data, Album::class, 'json', [
    //         AbstractNormalizer::OBJECT_TO_POPULATE => $album,
    //         'groups' => ['update']
    //     ]);

    //     $this->em->flush();

    //     return $this->json($album, 200, [], [
    //         'groups' => ['read'],
    //     ]);
    // }

    #[Route('/api/album/{id}', name: 'app_api_album_delete',  methods: ['DELETE'])]
    public function delete(Album $album): JsonResponse
    {
        $this->em->remove($album);
        $this->em->flush();

        return $this->json([
            'message' => 'Album deleted successfully'
        ], 200);
    }

}

src/Controller/Web/AlbumController.php
<?php

namespace App\Controller\Web;

use App\Entity\Album;
use App\Form\AlbumType;
use App\Repository\AlbumRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;


#[IsGranted('ROLE_ADMIN')]
#[Route('/album')]
class AlbumController extends AbstractController
{
    #[Route('/', name: 'app_web_album_index', methods: ['GET'])]
    public function index(AlbumRepository $albumRepository): Response
    {
        return $this->render('web/album/index.html.twig', [
            'albums' => $albumRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_web_album_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $album = new Album();
        $form = $this->createForm(AlbumType::class, $album);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($album);
            $entityManager->flush();

            return $this->redirectToRoute('app_web_album_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('web/album/new.html.twig', [
            'album' => $album,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_web_album_show', methods: ['GET'])]
    public function show(Album $album): Response
    {
        return $this->render('web/album/show.html.twig', [
            'album' => $album,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_web_album_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Album $album, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(AlbumType::class, $album);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_web_album_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('web/album/edit.html.twig', [
            'album' => $album,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_web_album_delete', methods: ['POST'])]
    public function delete(Request $request, Album $album, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$album->getId(), $request->getPayload()->get('_token'))) {
            $entityManager->remove($album);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_web_album_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/web/album/_delete_form.html.twig
<form method="post" action="{{ path('app_web_album_delete', {'id': album.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ album.id) }}">
    <button class="btn">Delete</button>
</form>

templates/web/album/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/web/album/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Album{% endblock %}

{% block body %}
    <h1>Edit Album</h1>

    {{ include('web/album/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_web_album_index') }}">back to list</a>

    {{ include('web/album/_delete_form.html.twig') }}
{% endblock %}

templates/web/album/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Album index{% endblock %}

{% block body %}
    <h1>Album index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Year</th>
                <th>Artist_id</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for album in albums %}
            <tr>
                <td>{{ album.id }}</td>
                <td>{{ album.name }}</td>
                <td>{{ album.year }}</td>
                <td>{{ album.artistId }}</td>
                <td>
                    <a href="{{ path('app_web_album_show', {'id': album.id}) }}">show</a>
                    <a href="{{ path('app_web_album_edit', {'id': album.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_web_album_new') }}">Create new</a>
{% endblock %}

templates/web/album/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Album{% endblock %}

{% block body %}
    <h1>Create new Album</h1>

    {{ include('web/album/_form.html.twig') }}

    <a href="{{ path('app_web_album_index') }}">back to list</a>
{% endblock %}

templates/web/album/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Album{% endblock %}

{% block body %}
    <h1>Album</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ album.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ album.name }}</td>
            </tr>
            <tr>
                <th>Year</th>
                <td>{{ album.year }}</td>
            </tr>
            <tr>
                <th>Artist_id</th>
                <td>{{ album.artistId }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_web_album_index') }}">back to list</a>

    <a href="{{ path('app_web_album_edit', {'id': album.id}) }}">edit</a>

    {{ include('web/album/_delete_form.html.twig') }}
{% endblock %}