src/Entity/Track.php
<?php

namespace App\Entity;

use App\Repository\TrackRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TrackRepository::class)]
class Track
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    private ?string $title = null;

    #[ORM\Column]
    private ?int $duration = null;

    #[ORM\Column]
    private ?int $album_id = null;

    /**
     * @var Collection<int, Album>
     */
    #[ORM\ManyToMany(targetEntity: Album::class, inversedBy: 'tracks')]
    private Collection $album;

    public function __construct()
    {
        $this->album = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getDuration(): ?int
    {
        return $this->duration;
    }

    public function setDuration(int $duration): static
    {
        $this->duration = $duration;

        return $this;
    }

    public function getAlbumId(): ?int
    {
        return $this->album_id;
    }

    public function setAlbumId(int $album_id): static
    {
        $this->album_id = $album_id;

        return $this;
    }

    /**
     * @return Collection<int, Album>
     */
    public function getAlbum(): Collection
    {
        return $this->album;
    }

    public function addAlbum(Album $album): static
    {
        if (!$this->album->contains($album)) {
            $this->album->add($album);
        }

        return $this;
    }

    public function removeAlbum(Album $album): static
    {
        $this->album->removeElement($album);

        return $this;
    }
}

src/Form/TrackType.php
<?php

namespace App\Form;

use App\Entity\Album;
use App\Entity\Track;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TrackType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title')
            ->add('duration')
            ->add('album_id')
            ->add('album', EntityType::class, [
                'class' => Album::class,
                'choice_label' => 'id',
                'multiple' => true,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Track::class,
        ]);
    }
}

src/Controller/Api/TrackController.php
<?php

namespace App\Controller\Api;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Routing\Attribute\Route;
use App\Entity\Track;
use App\Repository\TrackRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpKernel\Attribute\MapRequestPayload;
use Symfony\Component\Serializer\Normalizer\AbstractNormalizer;
use Symfony\Component\Messenger\Transport\Serialization\SerializerInterface;

class TrackController extends AbstractController
{
    public function __construct(
        private TrackRepository $trackRepository,
        private EntityManagerInterface $em,
        private SerializerInterface $serializer
    )
    {
        
    }
    #[Route('/api/track', name: 'app_api_track', methods: ['GET'])]
    public function index(): JsonResponse
    {
        $track = $this->trackRepository->findAll();

        return $this->json([
            'track' => $track,
        ], 200, [], [
            'groups' => ['read']
        ]);
    }

    #[Route('/api/track/{id}', name: 'app_api_track_get', methods: ['GET'])]
    public function get(?Track $track = null): JsonResponse
    {
        
        if(!$track)
        {
            return $this->json([
                'error' => 'Track does not exist',
            ], 404);
        }

        return $this->json($track, 200, [], [
            'groups' => ['read']
        ]);
    }

    #[Route('/api/track', name: 'app_api_track_add', methods: ['POST'])]
    public function add( #[MapRequestPayload('json', ['groups' => ['create']])] Track $track
    ): JsonResponse
    {
        $this->em->persist($track);
        $this->em->flush();

        return $this->json($track, 200, [], [
            'groups' => ['read']
        ]);
    }

    #[Route('/api/track/{id}', name: 'app_api_track_delete',  methods: ['DELETE'])]
    public function delete(Track $track): JsonResponse
    {
        $this->em->remove($track);
        $this->em->flush();

        return $this->json([
            'message' => 'Track deleted successfully'
        ], 200);
    }
}

src/Controller/Web/TrackController.php
<?php

namespace App\Controller\Web;

use App\Entity\Track;
use App\Form\TrackType;
use App\Repository\TrackRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[IsGranted('ROLE_ADMIN')]
#[Route('/web/track')]
class TrackController extends AbstractController
{
    #[Route('/', name: 'app_web_track_index', methods: ['GET'])]
    public function index(TrackRepository $trackRepository): Response
    {
        return $this->render('web/track/index.html.twig', [
            'tracks' => $trackRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_web_track_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $track = new Track();
        $form = $this->createForm(TrackType::class, $track);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($track);
            $entityManager->flush();

            return $this->redirectToRoute('app_web_track_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('web/track/new.html.twig', [
            'track' => $track,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_web_track_show', methods: ['GET'])]
    public function show(Track $track): Response
    {
        return $this->render('web/track/show.html.twig', [
            'track' => $track,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_web_track_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Track $track, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(TrackType::class, $track);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_web_track_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('web/track/edit.html.twig', [
            'track' => $track,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_web_track_delete', methods: ['POST'])]
    public function delete(Request $request, Track $track, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$track->getId(), $request->getPayload()->get('_token'))) {
            $entityManager->remove($track);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_web_track_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/web/track/_delete_form.html.twig
<form method="post" action="{{ path('app_web_track_delete', {'id': track.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ track.id) }}">
    <button class="btn">Delete</button>
</form>

templates/web/track/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/web/track/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Track{% endblock %}

{% block body %}
    <h1>Edit Track</h1>

    {{ include('web/track/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_web_track_index') }}">back to list</a>

    {{ include('web/track/_delete_form.html.twig') }}
{% endblock %}

templates/web/track/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Track index{% endblock %}

{% block body %}
    <h1>Track index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Title</th>
                <th>Duration</th>
                <th>Album_id</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for track in tracks %}
            <tr>
                <td>{{ track.id }}</td>
                <td>{{ track.title }}</td>
                <td>{{ track.duration }}</td>
                <td>{{ track.albumId }}</td>
                <td>
                    <a href="{{ path('app_web_track_show', {'id': track.id}) }}">show</a>
                    <a href="{{ path('app_web_track_edit', {'id': track.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_web_track_new') }}">Create new</a>
{% endblock %}

templates/web/track/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Track{% endblock %}

{% block body %}
    <h1>Create new Track</h1>

    {{ include('web/track/_form.html.twig') }}

    <a href="{{ path('app_web_track_index') }}">back to list</a>
{% endblock %}

templates/web/track/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Track{% endblock %}

{% block body %}
    <h1>Track</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ track.id }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ track.title }}</td>
            </tr>
            <tr>
                <th>Duration</th>
                <td>{{ track.duration }}</td>
            </tr>
            <tr>
                <th>Album_id</th>
                <td>{{ track.albumId }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_web_track_index') }}">back to list</a>

    <a href="{{ path('app_web_track_edit', {'id': track.id}) }}">edit</a>

    {{ include('web/track/_delete_form.html.twig') }}
{% endblock %}